# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('myurl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shorturl.MyURL')),
            ],
        ),
        migrations.CreateModel(
            name='ImpressionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('myurl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='shorturl.MyURL')),
            ],
        ),
    ]
