# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import shorturl.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, validators=[shorturl.validators.validate_url])),
                ('shortcode', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
